workflows:
  android-debug:
    name: Android Debug APK
    environment:
      flutter: "3.16.9" # ✅ 这样 Dart SDK 就是 3.5.0+
    scripts:
      - name: Install dependencies
        script: flutter pub get
      - name: Build debug APK
        script: flutter build apk --debug
    artifacts:
      - build/app/outputs/flutter-apk/app-debug.apk
